# Generated by Django 6.0.6 on 2026-07-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("company_name", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=100)),
                ("salary", models.IntegerField()),
                ("logo", models.ImageField(upload_to="logo")),
            ],
        ),
    ]
